In [6]:
import sys

sys.path.append('../')

import numpy as np
import graphviz
from IPython.display import display
from environments.tree.tree import NaryTreeEnvironment
from environments.tree.data import TrajectoryDataset, SetDataset
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.collections import LineCollection

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import hypll
from hypll.manifolds.poincare_ball import Curvature, PoincareBall
from hypll.optim import RiemannianAdam
import hypll.nn as hnn
from hypll.tensors import TangentTensor

import argparse
from environments.tree.data import GeneralTrajectoryDataset, get_maze_trajectories
from environments.tree.discrete_maze import GridMazeEnvironment
from networks.hypnets import HyperbolicMLP, manifold_map
from networks.nets import SmallEncoder
from utils import get_maze, load_model, load_tree_model
import os
import json


In [7]:
name = 'blank'
maze = get_maze(name)
maze = GridMazeEnvironment(maze)

maze.get_unflattened_valid_indices()

blank maze
i: 5, 3


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [8]:
trajectories = get_maze_trajectories(maze, 100)
num_actions = 5
dataset = GeneralTrajectoryDataset(
    trajectories=trajectories,
    valid_indices=maze.get_unflattened_valid_indices(),
    num_negatives=10,
    gamma=0.1
)

gamma: 0.1


In [11]:
dataset[2]

(array([67,  3]),
 array([77]),
 array([[78],
        [22],
        [37],
        [17],
        [68],
        [93],
        [72],
        [92],
        [41],
        [24]]))

In [4]:
tuple(np.array([0, 0]))

(0, 0)

In [2]:
dataset = SetDataset(
        depth=7,
        branching_factor=2,
        num_trajectories=100,
        num_negatives=11,
        gamma=0.1
    )

gamma: 0.1


In [18]:
a, b = dataset[3]

print(a.shape, b.shape)

[(68, 0), (33, 0), (16, 0), (7, 0), (3, 2), (8, 1), (17, 1), (35, 3)]
size1: 1, size2: 1
(1, 1) (1, 1)
